Replace GA with SA
pyvec/cz.pycon.org-2019 pull request #240
Opened 2021-11-01 18:54 UTC by honzajavorek

See https://pyvec.slack.com/archives/C12MP1GDB/p1635765591005700

![Screenshot 2021-11-01 at 19-54-03 Simple Analytics - Simple, clean, and privacy-friendly analytics](https://user-images.githubusercontent.com/283441/139725401-7c6b660d-5f65-4616-a70b-72ee10f06995.png)

2021-11-02 06:39 UTC, benabraham requested changes
si toho občas umazal moc
nezkoumal jsem všechny změny, když je to hned v prvním souboru

2021-11-02 06:39 UTC, benabraham commented on 2015/about/code-of-conduct.html
> -}
tady si toho smazal moc

2021-11-02 08:35 UTC, honzajavorek commented on 2015/about/code-of-conduct.html
> -}
díky, toho jsem si nevšiml (jiných pastí ano) 🤦

2021-11-02 09:07 UTC, honzajavorek commented
Zkus prosím znova, mělo by to být opraveno.

2021-11-02 16:55 UTC, benabraham commented
Kontrola 137 souborů zní jako hrozný peklo.

2021-11-02 20:16 UTC, honzajavorek commented
Mělo by stačit zkontrolovat aktuální šablonu v Djangu a pak nějaké jedno
html pro každý archivovány rok, zbytek bude stejný, nedelal jsem to ručně.

On Tue 2. 11. 2021 at 17:55, Daniel Srb ***@***.***> wrote:

> Kontrola 137 souborů zní jako hrozný peklo.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pyvec/cz.pycon.org-2019/pull/240#issuecomment-957942858>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACFGMIVWU7RIJYOF3ATDCTUKAJYLANCNFSM5HEWAO4Q>
> .
>

2021-11-03 07:18 UTC, benabraham approved these changes
🤞

2021-11-03 07:18 UTC, merged

2021-11-03 10:09 UTC, honzajavorek commented
Asi se ještě musí udělat deploy, co? Data zatím neproudí.